use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    tauri_build::build();
    generate_asset_table();
}

/// Walk `dist/` at compile time and generate a static asset table for the
/// HTTP daemon (see `src/serve.rs`): URL path, bytes via `include_bytes!`,
/// and content type.
///
/// `dist/` is gitignored, so a fresh worktree and any Rust-only CI step do
/// not have it. A missing `dist/` must NOT break the build: we emit a cargo
/// warning and generate an empty table, and the server then answers with a
/// clear "frontend not built" placeholder page.
fn generate_asset_table() {
    let manifest_dir = PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo"),
    );
    let dist = manifest_dir.join("dist");
    let out_dir =
        PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let generated = out_dir.join("asset_table.rs");

    // Track dist/ even when it does not exist yet: cargo reruns this script
    // once the path comes into existence.
    println!("cargo:rerun-if-changed={}", dist.display());

    let mut assets: Vec<(String, PathBuf, &'static str)> = Vec::new();
    if dist.is_dir() {
        collect_assets(&dist, &dist, &mut assets);
        assets.sort();
        println!(
            "cargo:warning=pc-ai-monitor-serve: embedded {} frontend asset(s) from dist/",
            assets.len()
        );
    } else {
        println!(
            "cargo:warning=pc-ai-monitor-serve: dist/ not found; the HTTP daemon will serve a placeholder page instead of the frontend (run `npm run build` to embed it)"
        );
    }

    let mut code = String::new();
    code.push_str("/// Generated by build.rs from dist/. Exact-match lookup only.\n");
    // Private: consumed inside `serve.rs` via include!, never exported.
    code.push_str("static ASSETS: &[Asset] = &[\n");
    if dist.is_dir() {
        for (route, file, content_type) in &assets {
            // Absolute path: the generated file lives in OUT_DIR, so relative
            // include_bytes! paths would resolve against the wrong directory.
            code.push_str(&format!(
                "    Asset {{ path: {route:?}, bytes: include_bytes!({file:?}), content_type: {content_type:?} }},\n"
            ));
        }
    }
    code.push_str("];\n");

    fs::write(&generated, code)
        .unwrap_or_else(|error| panic!("failed to write {}: {error}", generated.display()));
}

/// Recursively collect `(url_path, absolute_path, content_type)` for every
/// file under `dist/`. The root `index.html` is additionally published at
/// `/` so the daemon serves the dashboard on the bare host.
fn collect_assets(root: &Path, dir: &Path, assets: &mut Vec<(String, PathBuf, &'static str)>) {
    let entries = match fs::read_dir(dir) {
        Ok(entries) => entries,
        Err(error) => {
            println!("cargo:warning=pc-ai-monitor-serve: cannot read {}: {error}", dir.display());
            return;
        }
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_assets(root, &path, assets);
            continue;
        }
        let Some(relative) = path.strip_prefix(root).ok().map(|p| p.to_path_buf()) else {
            continue;
        };
        let url = path_to_url(&relative);
        let content_type = content_type_for(&relative);
        assets.push((url.clone(), path.clone(), content_type));
        if url == "/index.html" {
            // Also serve the entry point at "/".
            assets.push(("/".to_string(), path, content_type));
        }
    }
}

/// Convert a dist-relative path into a URL path with forward slashes.
fn path_to_url(relative: &Path) -> String {
    let mut url = String::from("/");
    for component in relative.components() {
        if !url.ends_with('/') {
            url.push('/');
        }
        url.push_str(&component.as_os_str().to_string_lossy());
    }
    url
}

/// Best-effort content type by extension. Assets are only ever served from
/// this fixed table, so the mapping is a compile-time concern.
fn content_type_for(path: &Path) -> &'static str {
    match path
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .as_str()
    {
        "html" | "htm" => "text/html; charset=utf-8",
        "js" | "mjs" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "json" | "map" => "application/json",
        "svg" => "image/svg+xml",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "gif" => "image/gif",
        "webp" => "image/webp",
        "ico" => "image/x-icon",
        "txt" => "text/plain; charset=utf-8",
        "woff" => "font/woff",
        "woff2" => "font/woff2",
        "ttf" => "font/ttf",
        "webmanifest" => "application/manifest+json",
        _ => "application/octet-stream",
    }
}
