//! Self-contained HTTP daemon that serves the dashboard without Tauri.
//!
//! This exists so macOS users (no GTK, no Python) can download a single
//! binary, run it, and open `http://localhost:PORT` in a browser. It also
//! works on Linux.
//!
//! Contract (do not change): `GET /api/state` returns exactly the same JSON
//! as the Tauri `get_state` command, i.e. the `GetState` shape from
//! `crate::collector`. The frontend already expects it.
//!
//! Only the Rust standard library is used: a local, single-user daemon that
//! answers a handful of GETs per second does not justify a web-framework
//! dependency. Connections are handled one thread each and closed after the
//! first response.
//!
//! The listener binds to `127.0.0.1` only: this is a local daemon, never a
//! network service. The port comes from `PC_AI_PORT` (defaults to
//! [`DEFAULT_PORT`]).
//!
//! When `dist/` existed at build time, `build.rs` embeds the frontend here as
//! an exact-match table ([`ASSETS`]); without it, every UI route answers with
//! a placeholder page explaining how to build the frontend.

use std::io::{BufRead, BufReader, Write};
use std::net::{SocketAddr, TcpListener, TcpStream};
use std::sync::Arc;
use std::thread::JoinHandle;

use parking_lot::Mutex;

use crate::collector::{start_sampling_loop, CollectorState, GetState, read_state};

/// Port used when `PC_AI_PORT` is unset or invalid.
pub const DEFAULT_PORT: u16 = 8787;

// ---------------------------------------------------------------------------
// Startup
// ---------------------------------------------------------------------------

/// Resolve the listen port from the environment.
pub fn port_from_env() -> u16 {
    std::env::var("PC_AI_PORT")
        .ok()
        .and_then(|raw| raw.trim().parse::<u16>().ok())
        .filter(|port| *port > 0)
        .unwrap_or(DEFAULT_PORT)
}

/// Entry point of the standalone binary: start the sampling loop and serve
/// HTTP until the process is killed.
pub fn run_daemon() -> std::io::Result<()> {
    let port = port_from_env();
    let state = start_sampling_loop();
    let listener = TcpListener::bind(("127.0.0.1", port))?;
    let addr = listener.local_addr()?;
    eprintln!("pc-ai-monitor: serving on http://{addr} (Ctrl-C to stop)");
    accept_loop(listener, state)
}

/// Bind an ephemeral listener in a background thread and return the bound
/// address plus the accept-loop handle. Used by tests and by anything that
/// wants to embed the server.
pub fn spawn_server(
    port: u16,
    state: Arc<Mutex<CollectorState>>,
) -> std::io::Result<(SocketAddr, JoinHandle<()>)> {
    let listener = TcpListener::bind(("127.0.0.1", port))?;
    let addr = listener.local_addr()?;
    let handle = std::thread::Builder::new()
        .name("http-serve".into())
        .spawn(move || {
            let _ = accept_loop(listener, state);
        })?;
    Ok((addr, handle))
}

/// Accept connections until the listener fails. One thread per connection.
fn accept_loop(listener: TcpListener, state: Arc<Mutex<CollectorState>>) -> std::io::Result<()> {
    for stream in listener.incoming() {
        {
            let stream = stream?;
            let state = Arc::clone(&state);
            std::thread::spawn(move || {
                let _ = handle_connection(stream, state);
            });
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Embedded frontend
// ---------------------------------------------------------------------------

/// One embedded frontend asset, generated by `build.rs` from `dist/`.
struct Asset {
    path: &'static str,
    bytes: &'static [u8],
    content_type: &'static str,
}

// Generated table: filled when `dist/` existed at build time, empty otherwise.
include!(concat!(env!("OUT_DIR"), "/asset_table.rs"));

/// Exact-match lookup against the generated table. There is deliberately no
/// path decoding and no filesystem fallback: a request path either equals a
/// table entry byte-for-byte or it is a 404. That makes `/%2e%2e/Cargo.toml`
/// and `/../Cargo.toml` indistinguishable from any other unknown path.
fn lookup_asset(path: &str) -> Option<&'static Asset> {
    ASSETS.iter().find(|asset| asset.path == path)
}

/// Page served for UI routes when the frontend was never embedded (no
/// `dist/` at build time).
fn placeholder_page() -> Asset {
    Asset {
        path: "/",
        bytes: br#"<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>pc-ai-monitor</title></head>
<body>
<h1>pc-ai-monitor</h1>
<p>The frontend has not been compiled into this binary.</p>
<p>Rebuild the project from a checkout with <code>npm install &amp;&amp; npm run build</code> and embed the assets by recompiling the Rust binary.</p>
<p>The JSON API is available at <code>/api/state</code>.</p>
</body>
</html>
"#,
        content_type: "text/html; charset=utf-8",
    }
}

// ---------------------------------------------------------------------------
// HTTP handling
// ---------------------------------------------------------------------------

/// Read one request, answer it, and close the connection.
fn handle_connection(stream: TcpStream, state: Arc<Mutex<CollectorState>>) -> std::io::Result<()> {
    // Answer a bounded number of requests so keep-alive clients cannot hang a
    // thread forever; still cheap, since each response closes promptly.
    stream.set_read_timeout(Some(std::time::Duration::from_secs(10)))?;
    stream.set_write_timeout(Some(std::time::Duration::from_secs(10)))?;

    let mut reader = BufReader::new(stream);
    let mut line = String::new();
    if reader.read_line(&mut line)? == 0 {
        return Ok(()); // client closed before sending anything
    }
    let request = parse_request_line(&line);
    drain_headers(&mut reader)?;

    let response = match request {
        Some(("GET", path)) => handle_get(&state, &path),
        Some(_) => Response::method_not_allowed(),
        None => Response::bad_request(),
    };
    response.write_to(reader.get_mut())
}

/// Split `METHOD SP TARGET SP HTTP/x.y` into its parts. The target keeps the
/// query string out of the way via [`path_only`].
fn parse_request_line(line: &str) -> Option<(&str, String)> {
    let mut parts = line.split_whitespace();
    let method = parts.next()?;
    let target = parts.next()?;
    // Third token is the HTTP version; its exact value does not matter here.
    parts.next()?;
    Some((method, path_only(target)))
}

/// Strip any query string from a request target. Fragment (`#`) never reaches
/// a server, but stripping it costs nothing.
fn path_only(target: &str) -> String {
    let path = target.split(['?', '#']).next().unwrap_or(target);
    path.to_string()
}

/// Consume the rest of the headers so the client does not get a connection
/// reset while we still owe it bytes.
fn drain_headers<R: BufRead>(reader: &mut R) -> std::io::Result<()> {
    let mut line = String::new();
    loop {
        line.clear();
        if reader.read_line(&mut line)? == 0 || line == "\r\n" || line == "\n" {
            return Ok(());
        }
    }
}

fn handle_get(state: &Arc<Mutex<CollectorState>>, path: &str) -> Response {
    if path == "/api/state" {
        Response::json(&state_payload(state))
    } else if let Some(asset) = lookup_asset(path) {
        Response::asset(asset)
    } else if path == "/" || path == "/index.html" {
        // No embedded frontend: explain instead of a bare 404.
        Response::asset(&placeholder_page())
    } else {
        Response::not_found()
    }
}

/// The exact `get_state` payload, serialized once per request.
fn state_payload(state: &Arc<Mutex<CollectorState>>) -> GetState {
    read_state(state)
}

// ---------------------------------------------------------------------------
// Responses
// ---------------------------------------------------------------------------

/// A minimal HTTP/1.1 response.
struct Response {
    status: &'static str,
    content_type: &'static str,
    body: Vec<u8>,
}

impl Response {
    fn json(body: &GetState) -> Self {
        let bytes = serde_json::to_vec(body).unwrap_or_else(|_| b"{}".to_vec());
        Self {
            status: "200 OK",
            content_type: "application/json",
            body: bytes,
        }
    }

    fn not_found() -> Self {
        Self::text("404 Not Found", "not found\n")
    }

    fn asset(asset: &Asset) -> Self {
        Self {
            status: "200 OK",
            content_type: asset.content_type,
            body: asset.bytes.to_vec(),
        }
    }

    fn method_not_allowed() -> Self {
        Self::text("405 Method Not Allowed", "only GET is supported\n")
    }

    fn bad_request() -> Self {
        Self::text("400 Bad Request", "malformed request\n")
    }

    fn text(status: &'static str, body: &str) -> Self {
        Self {
            status,
            content_type: "text/plain; charset=utf-8",
            body: body.as_bytes().to_vec(),
        }
    }

    fn write_to(&self, stream: &mut TcpStream) -> std::io::Result<()> {
        let head = format!(
            "HTTP/1.1 {}\r\nContent-Type: {}\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            self.status,
            self.content_type,
            self.body.len()
        );
        stream.write_all(head.as_bytes())?;
        stream.write_all(&self.body)?;
        stream.flush()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::{Read as _, Write as _};
    use std::net::TcpStream;
    use std::time::Duration;

    /// Start the real sampling loop on an ephemeral port, as a real client
    /// would see it.
    fn spawn_test_server() -> SocketAddr {
        let state = start_sampling_loop();
        let (addr, _handle) = spawn_server(0, state).expect("server should bind to port 0");
        addr
    }

    fn send_request(addr: SocketAddr, request: &str) -> String {
        let mut stream =
            TcpStream::connect(addr).expect("client should connect to the test server");
        stream
            .set_read_timeout(Some(Duration::from_secs(5)))
            .expect("read timeout should apply");
        stream
            .write_all(request.as_bytes())
            .expect("request should be written");
        let mut response = String::new();
        stream
            .read_to_string(&mut response)
            .expect("response should be readable until close");
        response
    }

    fn get(addr: SocketAddr, path: &str) -> String {
        send_request(
            addr,
            &format!("GET {path} HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"),
        )
    }

    #[test]
    fn api_state_matches_get_state_shape() {
        let addr = spawn_test_server();
        let response = get(addr, "/api/state");
        assert!(response.starts_with("HTTP/1.1 200 OK\r\n"), "got: {response}");
        assert!(response.contains("Content-Type: application/json"));

        let body = response
            .split_once("\r\n\r\n")
            .expect("headers should be separated from the body")
            .1;
        let json: serde_json::Value =
            serde_json::from_str(body).expect("body should be valid JSON");
        let keys = json
            .as_object()
            .expect("JSON body should be an object");
        // The contract: exactly the fields of `GetState`.
        assert_eq!(keys.len(), 2, "GetState must have exactly two keys");
        assert!(keys.contains_key("snapshot"));
        assert!(keys.contains_key("history"));
        assert!(
            keys["snapshot"].is_null() || keys["snapshot"].is_object(),
            "snapshot is Option<FullSnapshot>"
        );
        assert!(keys["history"].is_array(), "history is Vec<HistorySample>");
    }

    #[test]
    fn unknown_paths_return_404() {
        let addr = spawn_test_server();
        for path in ["/nope", "/api", "/api/", "/API/STATE", "/missing-forever.txt"] {
            let response = get(addr, path);
            assert!(
                response.starts_with("HTTP/1.1 404 Not Found\r\n"),
                "{path} should be 404, got: {response}"
            );
        }
    }

    #[test]
    fn path_traversals_are_rejected() {
        let addr = spawn_test_server();
        // Raw, percent-encoded and mixed traversals: all must fall through to
        // 404 because assets are matched exactly, never resolved on disk.
        for path in [
            "/../Cargo.toml",
            "/%2e%2e/Cargo.toml",
            "/..%2fCargo.toml",
            "/api/../Cargo.toml",
            "/../../etc/passwd",
        ] {
            let response = get(addr, path);
            assert!(
                response.starts_with("HTTP/1.1 404 Not Found\r\n"),
                "{path} should be 404, got: {response}"
            );
            assert!(
                !response.contains("[package]"),
                "{path} must never leak a source file"
            );
        }
    }

    #[test]
    fn root_serves_placeholder_or_embedded_frontend() {
        let addr = spawn_test_server();
        let response = get(addr, "/");
        assert!(response.starts_with("HTTP/1.1 200 OK\r\n"), "got: {response}");
        if ASSETS.is_empty() {
            // dist/ was not present at build time: the placeholder explains it.
            assert!(response.contains("Content-Type: text/html; charset=utf-8"));
            let body = response
                .split_once("\r\n\r\n")
                .expect("headers should be separated from the body")
                .1;
            assert!(
                body.contains("frontend") && body.contains("/api/state"),
                "placeholder should explain the missing frontend, got: {body}"
            );
        } else {
            // dist/ was embedded: the root serves the entry point.
            assert!(response.contains("Content-Type: text/html"));
        }
    }

    #[test]
    fn non_get_requests_are_rejected() {
        let addr = spawn_test_server();
        let response = send_request(
            addr,
            "POST /api/state HTTP/1.1\r\nHost: localhost\r\nContent-Length: 2\r\nConnection: close\r\n\r\n{}",
        );
        assert!(
            response.starts_with("HTTP/1.1 405 Method Not Allowed\r\n"),
            "got: {response}"
        );
    }

    #[test]
    fn port_from_env_reads_pc_ai_port() {
        // Env vars are process-global: serialize against any other test that
        // might read this variable.
        static ENV_LOCK: Mutex<()> = Mutex::new(());
        let _guard = ENV_LOCK.lock();

        std::env::set_var("PC_AI_PORT", "9123");
        assert_eq!(port_from_env(), 9123);

        std::env::set_var("PC_AI_PORT", "not-a-port");
        assert_eq!(port_from_env(), DEFAULT_PORT, "invalid value falls back");

        std::env::set_var("PC_AI_PORT", "0");
        assert_eq!(port_from_env(), DEFAULT_PORT, "port 0 is not a valid choice");

        std::env::remove_var("PC_AI_PORT");
        assert_eq!(port_from_env(), DEFAULT_PORT);
    }
}
